version: "3.9"

services:
  frontend:
    scale: 0

  db:
    restart: always
    env_file:
      - /home/ubuntu/env/jobtracker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate --noinput &&
             gunicorn JTA.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    expose:
      - "8000"
    env_file:
      - /home/ubuntu/env/jobtracker.env
    environment:
      - POSTGRES_HOST=db
      - DJANGO_ENV=production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/mediafiles

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/mediafiles

volumes:
  postgres_data:
  static_files:
  media_files:
