# Generated by Django 6.0 on 2026-01-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='Comment',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Applied', max_length=20),
        ),
        migrations.AddField(
            model_name='jobs',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
