# Generated by Django 6.0 on 2026-01-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobs_comment_alter_jobs_status_jobs_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='job_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job_name',
            new_name='position',
        ),
    ]
